import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  ArrowLeft, Brain, AlertTriangle, CalendarDays,
  Lightbulb, MessageSquare, BarChart3, Tag, ShieldAlert,
  ClipboardList, FileText, Sparkles, User, Trash2, Loader2,
} from 'lucide-react'
import toast from 'react-hot-toast'
import { preAssessmentAPI } from '@/api'
import { formatDate, formatTime, timeAgo, RISK_LEVEL_CONFIG, LIKERT_LABELS } from '@/lib/utils'
import Avatar from '@/components/ui/Avatar'
import Modal from '@/components/ui/Modal'
import ResourceTypeIcon from '@/components/ui/ResourceTypeIcon'

const URGENCY_COLORS = {
  Low:       'bg-slate-100 text-slate-600 border-slate-200',
  Moderate:  'bg-blue-50 text-blue-700 border-blue-200',
  High:      'bg-orange-50 text-orange-700 border-orange-200',
  Immediate: 'bg-red-50 text-red-700 border-red-200',
  Crisis:    'bg-red-50 text-red-700 border-red-200',
}

const COUNSELOR_DISCLAIMER = `Counselor Notice: The outputs generated by this system are based on predefined rules, assessment responses, and available guidance resources. These outputs are intended only as preliminary support information and should not replace professional judgment, counselor expertise, case assessment, or institutional procedures. Guidance Counselors retain full authority and responsibility for all counseling decisions, interventions, referrals, and recommendations.`

export default function PreAssessmentDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [assessment, setAssessment] = useState(null)
  const [loading, setLoading] = useState(true)
  const [confirmDelete, setConfirmDelete] = useState(false)
  const [deleting, setDeleting] = useState(false)

  const handleDelete = async () => {
    setDeleting(true)
    try {
      await preAssessmentAPI.delete(id)
      toast.success('Pre-assessment deleted')
      navigate('/counselor/pre-assessments')
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to delete pre-assessment')
      setDeleting(false)
      setConfirmDelete(false)
    }
  }

  useEffect(() => {
    preAssessmentAPI.getById(id)
      .then(({ data }) => setAssessment(data))
      .catch(() => navigate(-1))
      .finally(() => setLoading(false))
  }, [id, navigate])

  if (loading) {
    return (
      <div className="space-y-4">
        <div className="skeleton h-8 w-48 rounded-xl" />
        <div className="skeleton h-64 rounded-2xl" />
        <div className="skeleton h-48 rounded-2xl" />
      </div>
    )
  }

  if (!assessment) return null

  const ar      = assessment.assessmentResults
  const legacy  = assessment.aiRecommendations
  const student = assessment.studentId
  const appt    = assessment.appointmentId
  const snap    = assessment.studentSnapshot || {}
  const riskCfg = ar?.riskLevel ? RISK_LEVEL_CONFIG[ar.riskLevel] : null

  const isUrgent =
    ar?.riskLevel === 'Critical' ||
    assessment.urgencyLevel === 'Immediate' ||
    assessment.urgencyLevel === 'Crisis' ||
    legacy?.urgencyFlag

  return (
    <div className="animate-fade-in max-w-6xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <button onClick={() => navigate(-1)} className="btn-ghost -ml-2">
          <ArrowLeft size={16} /> Back to Pre-Assessments
        </button>
        <button
          onClick={() => setConfirmDelete(true)}
          className="flex items-center gap-1.5 text-sm font-semibold text-red-600 hover:text-red-700 px-3 py-1.5 rounded-lg hover:bg-red-50 transition-colors"
        >
          <Trash2 size={15} /> Delete
        </button>
      </div>

      {/* Counselor notice */}
      <div className="mb-5 p-4 bg-slate-50 border border-slate-200 rounded-xl">
        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-1">Counselor Notice</p>
        <p className="text-xs text-slate-500 leading-relaxed">{COUNSELOR_DISCLAIMER}</p>
      </div>

      {/* Student info header */}
      <div className="card mb-5">
        <div className="flex items-start gap-4">
          <Avatar name={student?.fullName} size="lg" />
          <div className="flex-1">
            <h1 className="font-display text-2xl text-slate-900">{student?.fullName}</h1>
            <p className="text-slate-500 text-sm mt-0.5">
              {student?.course || snap.course}{(student?.yearLevel || snap.yearLevel) ? ` · ${student?.yearLevel || snap.yearLevel}` : ''}
              {snap.section ? ` · ${snap.section}` : ''}
              {(student?.studentIDnum || snap.studentIDnum) ? ` · ${student?.studentIDnum || snap.studentIDnum}` : ''}
            </p>
            <div className="flex items-center gap-3 mt-3 flex-wrap">
              {riskCfg ? (
                <span className={`badge border ${riskCfg.border} ${riskCfg.bg} ${riskCfg.color}`}>
                  <ShieldAlert size={10} /> {riskCfg.label}
                </span>
              ) : (
                <span className={`badge border ${URGENCY_COLORS[assessment.urgencyLevel] || URGENCY_COLORS.Low}`}>
                  {(assessment.urgencyLevel === 'Immediate' || assessment.urgencyLevel === 'Crisis') && <AlertTriangle size={10} />}
                  {assessment.urgencyLevel} Urgency
                </span>
              )}
              {ar?.detectedCategory && (
                <span className="badge bg-primary-100 text-primary-700">{ar.detectedCategory}</span>
              )}
              {!ar && assessment.primaryConcern && (
                <span className="badge bg-slate-100 text-slate-600">{assessment.primaryConcern}</span>
              )}
              <span className="text-xs text-slate-400">{timeAgo(assessment.createdAt)}</span>
            </div>
          </div>
          {appt && (
            <div className="text-right bg-surface-50 rounded-xl p-3 border border-surface-200 shrink-0">
              <p className="text-xs text-slate-500 mb-1">Linked Appointment</p>
              <p className="text-sm font-semibold text-slate-800">{formatDate(appt.date)}</p>
              <p className="text-xs text-slate-500">{formatTime(appt.startTime)} – {formatTime(appt.endTime)}</p>
            </div>
          )}
        </div>
      </div>

      {/* Student Information (Section A — as provided on the form) */}
      <div className="card mb-5">
        <div className="flex items-center gap-2 mb-3">
          <User size={15} className="text-slate-500" />
          <h2 className="font-display text-lg text-slate-900">Student Information</h2>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-4 gap-y-3 text-sm">
          <div>
            <p className="text-xs text-slate-400">Student ID</p>
            <p className="text-slate-800 font-medium">{student?.studentIDnum || snap.studentIDnum || '—'}</p>
          </div>
          <div>
            <p className="text-xs text-slate-400">Course</p>
            <p className="text-slate-800 font-medium">{student?.course || snap.course || '—'}</p>
          </div>
          <div>
            <p className="text-xs text-slate-400">Year &amp; Section</p>
            <p className="text-slate-800 font-medium">
              {(student?.yearLevel || snap.yearLevel) || '—'}{snap.section ? ` · ${snap.section}` : ''}
            </p>
          </div>
          <div>
            <p className="text-xs text-slate-400">Age</p>
            <p className="text-slate-800 font-medium">{snap.age != null ? snap.age : '—'}</p>
          </div>
          <div>
            <p className="text-xs text-slate-400">Gender</p>
            <p className="text-slate-800 font-medium">{snap.gender || '—'}</p>
          </div>
          <div>
            <p className="text-xs text-slate-400">Contact Number</p>
            <p className="text-slate-800 font-medium">{snap.contactNumber || '—'}</p>
          </div>
          <div className="col-span-2 sm:col-span-3">
            <p className="text-xs text-slate-400">Email</p>
            <p className="text-slate-800 font-medium">{student?.email || snap.email || '—'}</p>
          </div>
        </div>
      </div>

      {/* Crisis alert */}
      {isUrgent && (
        <div className="mb-5 flex items-start gap-3 p-4 bg-red-50 border border-red-300 rounded-2xl">
          <AlertTriangle size={18} className="text-red-500 shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-bold text-red-700">Critical/Immediate Attention Recommended</p>
            <p className="text-xs text-red-600 mt-0.5 leading-relaxed">
              Assessment responses suggest elevated risk. Please review the student's responses
              carefully and prioritize this session. Use professional judgment to assess safety.
            </p>
          </div>
        </div>
      )}

      {/* ── ASSESSMENT RESULTS (new engine output) ── */}
      {ar && (
        <div className="card mb-5 border-2 border-primary-200">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-8 h-8 rounded-lg bg-primary-100 flex items-center justify-center">
              <Brain size={16} className="text-primary-600" />
            </div>
            <h2 className="font-display text-lg text-slate-900">Preliminary Assessment Analysis</h2>
            <span className="ml-auto text-[10px] font-bold uppercase tracking-wider text-slate-400 bg-slate-100 px-2 py-0.5 rounded-full">
              Suggestive Insights
            </span>
          </div>

          {/* Category + Risk */}
          <div className="grid grid-cols-2 gap-3 mb-4">
            <div className="bg-slate-50 rounded-xl p-3 border border-slate-200">
              <p className="text-xs text-slate-400 mb-1">Detected Concern Area</p>
              <p className="text-sm font-semibold text-slate-800">{ar.detectedCategory}</p>
              <p className="text-[10px] text-slate-400 mt-1 italic">Responses may indicate this area.</p>
            </div>
            {riskCfg && (
              <div className={`rounded-xl p-3 border ${riskCfg.border} ${riskCfg.bg}`}>
                <p className="text-xs text-slate-400 mb-1">Preliminary Risk Level</p>
                <p className={`text-sm font-semibold ${riskCfg.color}`}>{riskCfg.label}</p>
                <p className="text-[10px] text-slate-400 mt-1 italic">Based on Likert score analysis.</p>
              </div>
            )}
          </div>

          {/* Score Breakdown */}
          {ar.scoreBreakdown && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-slate-500 mb-2">Score Breakdown (avg per domain, 1–5 scale)</p>
              <div className="grid grid-cols-5 gap-2">
                {Object.entries(ar.scoreBreakdown)
                  .filter(([k]) => k !== 'average')
                  .map(([domain, rawScore]) => {
                    const score = Number(rawScore ?? 0)
                    return (
                      <div key={domain} className="text-center">
                        <div className="text-xs text-slate-400 capitalize mb-1">{domain}</div>
                        <div className={`text-sm font-bold rounded-lg py-1 ${
                          score >= 4 ? 'bg-red-100 text-red-700' :
                          score >= 3 ? 'bg-amber-100 text-amber-700' :
                          'bg-emerald-100 text-emerald-700'}`}>
                          {score.toFixed(1)}
                        </div>
                      </div>
                    )
                  })}
              </div>
              {ar.scoreBreakdown.average != null && (
                <p className="text-xs text-slate-500 mt-2 text-right">
                  Overall average: <strong>{Number(ar.scoreBreakdown.average).toFixed(2)}</strong>
                </p>
              )}
            </div>
          )}

          {/* Risk Factors */}
          {ar.riskFactors?.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-slate-500 mb-2 flex items-center gap-1">
                <ShieldAlert size={12} /> Possible concerns identified
              </p>
              <ul className="space-y-1.5">
                {ar.riskFactors.map((f, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary-400 mt-1.5 shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Suggested Resources */}
          {ar.suggestedResources?.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-slate-500 mb-2 flex items-center gap-1">
                <Lightbulb size={12} /> Suggested resources for consideration
              </p>
              <div className="space-y-2">
                {ar.suggestedResources.map((r, i) => (
                  <div key={i} className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl border border-slate-200">
                    <span className="w-8 h-8 rounded-lg bg-white border border-slate-200 flex items-center justify-center shrink-0">
                      <ResourceTypeIcon type={r.type} size={16} className="text-primary-500" />
                    </span>
                    <div>
                      <p className="text-sm font-semibold text-slate-800">{r.title}</p>
                      {r.description && <p className="text-xs text-slate-500 mt-0.5">{r.description}</p>}
                      <span className="mt-1 inline-block text-[10px] px-2 py-0.5 rounded-full bg-white border border-slate-200 text-slate-500 capitalize">{r.type}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Suggested Next Action */}
          {ar.suggestedNextAction && (
            <div className="mb-4 p-3 bg-primary-50 rounded-xl border border-primary-100">
              <p className="text-xs font-semibold text-primary-700 mb-1">Suggested next action</p>
              <p className="text-sm text-slate-700">{ar.suggestedNextAction}</p>
            </div>
          )}

          {/* Counselor Preparation Notes */}
          {ar.counselorPreparationNotes && (
            <div className="p-4 bg-amber-50 rounded-xl border border-amber-200">
              <p className="text-xs font-semibold text-amber-700 mb-1.5 flex items-center gap-1">
                <MessageSquare size={12} /> Counselor Preparation Notes
              </p>
              <p className="text-sm text-slate-700 leading-relaxed">{ar.counselorPreparationNotes}</p>
            </div>
          )}

          {/* Counselor Summary (Gemini) */}
          {ar.counselorSummary && (
            <div className="mt-4 p-4 bg-white rounded-xl border border-slate-200">
              <div className="flex items-center gap-1.5 mb-1.5">
                <Sparkles size={12} className="text-primary-400" />
                <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">AI-Generated Summary</p>
              </div>
              <p className="text-sm text-slate-700 italic leading-relaxed">{ar.counselorSummary}</p>
              {ar.geminiUsed && (
                <p className="text-[10px] text-slate-400 mt-2">Generated by AI — use as supplementary context only.</p>
              )}
            </div>
          )}
        </div>
      )}

      {/* ── Legacy AI Recommendations (old submissions) ── */}
      {!ar && legacy && (
        <div className={`card mb-5 border-2 ${legacy.urgencyFlag ? 'border-red-300 bg-red-50/30' : 'border-primary-200 bg-primary-50/20'}`}>
          <div className="flex items-center gap-2 mb-4">
            <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${legacy.urgencyFlag ? 'bg-red-100' : 'bg-primary-100'}`}>
              <Brain size={16} className={legacy.urgencyFlag ? 'text-red-600' : 'text-primary-600'} />
            </div>
            <h2 className="font-display text-lg text-slate-900">AI Analysis (Legacy)</h2>
            {legacy.urgencyFlag && (
              <span className="badge bg-red-100 text-red-600 ml-auto">
                <AlertTriangle size={10} /> Urgent
              </span>
            )}
            <span className="text-xs text-slate-400 ml-auto">{legacy.model}</span>
          </div>

          {legacy.summary && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Summary</p>
              <p className="text-sm text-slate-700 leading-relaxed bg-white rounded-xl p-4 border border-surface-200">
                {legacy.summary}
              </p>
            </div>
          )}

          {legacy.interventions?.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2 flex items-center gap-1">
                <Lightbulb size={12} /> Suggested Interventions
              </p>
              <ul className="space-y-2">
                {legacy.interventions.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                    <span className="w-5 h-5 rounded-full bg-primary-100 text-primary-600 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">{i + 1}</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {legacy.counselorTips && (
            <div className="bg-white rounded-xl p-4 border border-surface-200">
              <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2 flex items-center gap-1">
                <MessageSquare size={12} /> Session Approach Tips
              </p>
              <p className="text-sm text-slate-700 italic">{legacy.counselorTips}</p>
            </div>
          )}
        </div>
      )}

      {/* ── Reference sections (flow into two columns on desktop) ── */}
      <div className="grid lg:grid-cols-2 gap-5 items-start [&>.card]:mb-0">
      {/* ── Purpose of Visit ── */}
      {assessment.purposeOfVisit?.length > 0 && (
        <div className="card mb-5">
          <div className="flex items-center gap-2 mb-3">
            <ClipboardList size={15} className="text-slate-500" />
            <h2 className="font-display text-lg text-slate-900">Purpose of Visit</h2>
          </div>
          <div className="flex flex-wrap gap-2">
            {assessment.purposeOfVisit.map((p) => (
              <span key={p} className="text-xs px-3 py-1.5 rounded-full bg-primary-100 text-primary-700 font-medium">{p}</span>
            ))}
            {assessment.purposeOfVisitOther && (
              <span className="text-xs px-3 py-1.5 rounded-full bg-primary-100 text-primary-700 font-medium">{assessment.purposeOfVisitOther}</span>
            )}
          </div>
        </div>
      )}

      {/* ── Likert Responses ── */}
      {assessment.likertResponses?.length > 0 && (
        <div className="card mb-5">
          <div className="flex items-center gap-2 mb-4">
            <BarChart3 size={15} className="text-slate-500" />
            <h2 className="font-display text-lg text-slate-900">Self-Assessment Responses</h2>
          </div>
          <div className="space-y-2">
            {assessment.likertResponses.map((r, i) => (
              <div key={i} className="flex items-center justify-between gap-3 py-2 border-b border-slate-100 last:border-0">
                <p className="text-sm text-slate-700 flex-1">{i + 1}. {r.statement}</p>
                <span className={`text-xs font-bold px-3 py-1 rounded-full shrink-0
                  ${r.score >= 4 ? 'bg-red-100 text-red-700' : r.score === 3 ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'}`}>
                  {r.score} – {LIKERT_LABELS[r.score]}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Concern Categories ── */}
      {assessment.concernCategories?.length > 0 && (
        <div className="card mb-5">
          <div className="flex items-center gap-2 mb-3">
            <Tag size={15} className="text-slate-500" />
            <h2 className="font-display text-lg text-slate-900">Selected Concern Categories</h2>
          </div>
          <div className="flex flex-wrap gap-2">
            {assessment.concernCategories.map((c) => (
              <span key={c} className="text-xs px-2.5 py-1 rounded-full bg-slate-200 text-slate-700 font-medium">{c}</span>
            ))}
          </div>
        </div>
      )}

      {/* ── Student Description ── */}
      <div className="card mb-5">
        <div className="flex items-center gap-2 mb-3">
          <FileText size={15} className="text-slate-500" />
          <h2 className="font-display text-lg text-slate-900">Student's Description</h2>
        </div>
        <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap bg-surface-50 rounded-xl p-4 border border-surface-200">
          {assessment.concernDescription}
        </p>
        {assessment.concernDuration && (
          <p className="text-xs text-slate-500 mt-3">
            Duration: <strong>{assessment.concernDuration}</strong>
          </p>
        )}
        {assessment.expectedAssistance && (
          <div className="mt-3">
            <p className="text-xs font-semibold text-slate-500 mb-1">Expected assistance from Guidance Office:</p>
            <p className="text-sm text-slate-600 bg-surface-50 rounded-xl p-3 border border-surface-200 italic">
              "{assessment.expectedAssistance}"
            </p>
          </div>
        )}
        <p className="text-xs text-slate-500 mt-3">
          Self-reported urgency: <strong>{assessment.urgencyLevel}</strong>
        </p>
      </div>

      {/* ── Legacy Questionnaire Responses ── */}
      {!assessment.likertResponses?.length && assessment.responses?.length > 0 && (
        <div className="card mb-5">
          <h2 className="font-display text-lg text-slate-900 mb-5">Questionnaire Responses</h2>
          <div className="space-y-5">
            {assessment.responses.map((r, i) => (
              <div key={i}>
                <p className="text-xs font-semibold text-slate-500 mb-1">{i + 1}. {r.question}</p>
                <p className="text-sm text-slate-700 bg-surface-50 rounded-xl p-3 border border-surface-200">{r.answer}</p>
              </div>
            ))}
          </div>
        </div>
      )}
      </div>{/* end reference sections grid */}

      {/* ── Delete confirmation ── */}
      <Modal isOpen={confirmDelete} onClose={() => !deleting && setConfirmDelete(false)} title="Delete Pre-Assessment">
        <div className="space-y-4">
          <div className="flex items-start gap-3 p-4 bg-red-50 border border-red-200 rounded-xl">
            <AlertTriangle size={18} className="text-red-500 shrink-0 mt-0.5" />
            <p className="text-sm text-red-700 leading-relaxed">
              This permanently deletes the student's pre-assessment and all its details and results.
              This action cannot be undone.
            </p>
          </div>
          <div className="flex justify-end gap-2">
            <button onClick={() => setConfirmDelete(false)} disabled={deleting} className="btn btn-outline btn-sm">
              Cancel
            </button>
            <button onClick={handleDelete} disabled={deleting} className="btn btn-error btn-sm text-white gap-1.5">
              {deleting ? <><Loader2 size={14} className="animate-spin" /> Deleting…</> : <><Trash2 size={14} /> Delete</>}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  )
}
