import { useLocation, useNavigate } from 'react-router-dom'
import { useEffect } from 'react'
import {
  CalendarDays, BookOpen, AlertTriangle, ArrowRight, Home,
  CheckCircle2, Brain, Sparkles, ExternalLink, BarChart3,
  ShieldAlert, Tag,
} from 'lucide-react'
import { RISK_LEVEL_CONFIG } from '@/lib/utils'
import ResourceTypeIcon from '@/components/ui/ResourceTypeIcon'

const DISCLAIMER_STUDENT = `The information generated by this pre-assessment is intended only to assist the Guidance Office in understanding your concerns and preparing for counseling sessions. The results are suggestive in nature and should be interpreted with discretion. They do not constitute professional counseling, diagnosis, treatment, or psychological evaluation. Only a qualified Guidance Counselor can properly assess your situation.`

export default function PreAssessmentResults() {
  const location = useLocation()
  const navigate  = useNavigate()

  const {
    assessmentResults: ar,
    aiRecommendations: legacy,
    preAssessmentId,
    urgencyLevel,
    purposeOfVisit,
  } = location.state || {}

  useEffect(() => {
    if (!preAssessmentId) navigate('/student/pre-assessment', { replace: true })
  }, [preAssessmentId, navigate])

  if (!preAssessmentId) return null

  const isUrgent =
    ar?.riskLevel === 'Critical' ||
    urgencyLevel === 'Immediate' ||
    urgencyLevel === 'Crisis' ||
    legacy?.urgencyFlag

  const riskCfg = ar?.riskLevel ? RISK_LEVEL_CONFIG[ar.riskLevel] : null

  const handleBook = () =>
    navigate(`/student/book?preAssessmentId=${preAssessmentId}`)

  // New engine results
  if (ar) {
    return (
      <div className="animate-fade-in max-w-2xl">
        {/* Header */}
        <div className="page-header">
          <div className="flex items-center gap-3 mb-1">
            <div className="w-9 h-9 rounded-xl bg-primary-100 flex items-center justify-center">
              <Brain size={18} className="text-primary-600" />
            </div>
            <h1 className="page-title mb-0">Assessment Results</h1>
          </div>
          <p className="page-subtitle">
            Preliminary suggestive insights prepared for your Guidance Counselor
          </p>
        </div>

        {/* Crisis banner */}
        {isUrgent && (
          <div className="mb-5 flex items-start gap-3 p-4 bg-red-50 border border-red-300 rounded-2xl">
            <AlertTriangle size={18} className="text-red-500 shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-bold text-red-700">Immediate Support Available</p>
              <p className="text-xs text-red-600 mt-0.5 leading-relaxed">
                If you feel unsafe or are in crisis, please contact{' '}
                <strong>Hopeline PH: 02-8804-4673</strong> or go to the Guidance Office immediately.
              </p>
            </div>
          </div>
        )}

        {/* Purpose of Visit pills */}
        {purposeOfVisit?.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-5">
            {purposeOfVisit.map((p) => (
              <span key={p} className="text-xs px-3 py-1.5 rounded-full bg-primary-100 text-primary-700 font-medium">{p}</span>
            ))}
            <span className={`text-xs px-3 py-1.5 rounded-full font-medium ${
              urgencyLevel === 'Immediate' ? 'bg-red-100 text-red-700' :
              urgencyLevel === 'High'      ? 'bg-orange-100 text-orange-700' :
              urgencyLevel === 'Moderate'  ? 'bg-amber-100 text-amber-700' :
                                             'bg-slate-100 text-slate-600'
            }`}>
              {urgencyLevel} Urgency
            </span>
          </div>
        )}

        {/* SUGGESTIVE INSIGHTS label */}
        <div className="mb-2">
          <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400 bg-slate-100 px-3 py-1 rounded-full">
            Preliminary Guidance Support Information
          </span>
        </div>

        {/* Detected Category + Risk Level */}
        <div className="grid grid-cols-2 gap-3 mb-5">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-4">
            <div className="flex items-center gap-2 mb-2">
              <Tag size={14} className="text-primary-500" />
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide">Concern Area</p>
            </div>
            <p className="text-sm font-semibold text-slate-800 leading-snug">{ar.detectedCategory}</p>
            <p className="text-[10px] text-slate-400 mt-1 italic">The responses may indicate this area.</p>
          </div>
          {riskCfg && (
            <div className={`rounded-2xl border ${riskCfg.border} shadow-sm p-4 ${riskCfg.bg}`}>
              <div className="flex items-center gap-2 mb-2">
                <ShieldAlert size={14} className={riskCfg.color} />
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide">Risk Level</p>
              </div>
              <p className={`text-sm font-semibold ${riskCfg.color}`}>{riskCfg.label}</p>
              <p className="text-[10px] text-slate-400 mt-1 italic">Based on your self-assessment scores.</p>
            </div>
          )}
        </div>

        {/* Risk Factors */}
        {ar.riskFactors?.length > 0 && (
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5 mb-5">
            <div className="flex items-center gap-2 mb-3">
              <BarChart3 size={15} className="text-slate-500" />
              <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
                Areas That May Warrant Further Exploration
              </p>
            </div>
            <ul className="space-y-2">
              {ar.riskFactors.map((f, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary-400 mt-1.5 shrink-0" />
                  {f}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Student Summary (Gemini) */}
        {ar.studentSummary && (
          <div className="bg-primary-50 border border-primary-200 rounded-2xl p-5 mb-5">
            <div className="flex items-center gap-2 mb-2">
              <Sparkles size={14} className="text-primary-500" />
              <p className="text-xs font-semibold text-primary-600 uppercase tracking-wide">A Note for You</p>
            </div>
            <p className="text-sm text-slate-700 leading-relaxed italic">{ar.studentSummary}</p>
          </div>
        )}

        {/* Suggested Resources */}
        {ar.suggestedResources?.length > 0 && (
          <div className="mb-5">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-3">
              Suggested Resources for Consideration
            </p>
            <div className="space-y-2">
              {ar.suggestedResources.map((r, i) => (
                <div key={i} className="flex items-start gap-3 p-4 bg-white rounded-xl border border-slate-200 shadow-sm">
                  <span className="w-9 h-9 rounded-lg bg-primary-50 flex items-center justify-center shrink-0">
                    <ResourceTypeIcon type={r.type} size={18} className="text-primary-500" />
                  </span>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-slate-800">{r.title}</p>
                    {r.description && (
                      <p className="text-xs text-slate-500 mt-0.5 leading-relaxed">{r.description}</p>
                    )}
                    <span className="mt-1 inline-block text-[10px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-500 font-medium capitalize">
                      {r.type}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Suggested Next Action */}
        {ar.suggestedNextAction && (
          <div className="bg-white rounded-2xl border border-primary-200 shadow-sm p-5 mb-5">
            <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-2">Suggested Next Action</p>
            <p className="text-sm text-slate-700 leading-relaxed">{ar.suggestedNextAction}</p>
          </div>
        )}

        {/* Disclaimer */}
        <div className="p-4 bg-amber-50 border border-amber-200 rounded-2xl mb-5">
          <p className="text-xs font-semibold text-amber-800 mb-1.5">Important Notice</p>
          <p className="text-xs text-amber-700 leading-relaxed">{DISCLAIMER_STUDENT}</p>
        </div>

        {/* CTAs */}
        <div className="card space-y-3">
          <p className="text-xs text-slate-500 font-medium">What would you like to do next?</p>
          <button
            onClick={handleBook}
            className="btn-primary w-full flex items-center justify-center gap-2"
          >
            <CalendarDays size={16} /> Book a Counseling Session
            <ArrowRight size={15} className="ml-auto" />
          </button>
          <div className="flex items-center gap-2 p-3 bg-emerald-50 border border-emerald-100 rounded-xl">
            <CheckCircle2 size={14} className="text-emerald-500 shrink-0" />
            <p className="text-xs text-emerald-700 leading-relaxed">
              <strong>Saved:</strong> Your assessment is stored and will be accessible to your
              guidance counselor once you book an appointment.
            </p>
          </div>
          <button
            onClick={() => navigate('/student/dashboard')}
            className="w-full text-center text-sm text-slate-400 hover:text-slate-600 py-1.5 transition-colors flex items-center justify-center gap-1.5"
          >
            <Home size={13} /> Return to dashboard
          </button>
        </div>
      </div>
    )
  }

  // ── Legacy fallback: old AI format or no results ────────────────────────────
  if (legacy) {
    return (
      <div className="animate-fade-in max-w-2xl">
        <div className="page-header">
          <h1 className="page-title">Assessment Results</h1>
          <p className="page-subtitle">Based on your responses</p>
        </div>
        {isUrgent && (
          <div className="mb-5 flex items-start gap-3 p-4 bg-red-50 border border-red-300 rounded-2xl">
            <AlertTriangle size={18} className="text-red-500 shrink-0 mt-0.5" />
            <p className="text-xs text-red-600 mt-0.5 leading-relaxed">
              <strong>Immediate Support Available:</strong> Hopeline PH: 02-8804-4673
            </p>
          </div>
        )}
        <div className="card mb-5">
          {legacy.studentFacingMessage && (
            <p className="text-sm text-slate-700 leading-relaxed mb-4">{legacy.studentFacingMessage}</p>
          )}
          {legacy.summary && (
            <p className="text-sm text-slate-600 italic leading-relaxed bg-surface-50 rounded-xl p-4 border border-surface-200">
              {legacy.summary}
            </p>
          )}
          {legacy.studentResources?.length > 0 && (
            <div className="mt-4 space-y-2">
              {legacy.studentResources.map((r, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-white rounded-xl border border-slate-200">
                  <BookOpen size={14} className="text-slate-400 mt-0.5 shrink-0" />
                  <div>
                    <p className="text-sm font-semibold text-slate-800">{r.title}</p>
                    {r.description && <p className="text-xs text-slate-500 mt-0.5">{r.description}</p>}
                  </div>
                  {r.link && (
                    <a href={r.link} target="_blank" rel="noopener noreferrer" className="ml-auto shrink-0 text-primary-500">
                      <ExternalLink size={13} />
                    </a>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
        <div className="p-4 bg-amber-50 border border-amber-200 rounded-xl mb-5">
          <p className="text-xs text-amber-700 leading-relaxed">{DISCLAIMER_STUDENT}</p>
        </div>
        <div className="card space-y-3">
          <button onClick={handleBook} className="btn-primary w-full flex items-center justify-center gap-2">
            <CalendarDays size={16} /> Book an Appointment
          </button>
          <button onClick={() => navigate('/student/dashboard')}
            className="w-full text-center text-sm text-slate-400 hover:text-slate-600 py-1.5 transition-colors flex items-center justify-center gap-1.5">
            <Home size={13} /> Return to dashboard
          </button>
        </div>
      </div>
    )
  }

  // ── No results at all (AI unavailable and no engine result) ─────────────────
  return (
    <div className="animate-fade-in max-w-2xl">
      <div className="page-header">
        <h1 className="page-title">Assessment Submitted</h1>
      </div>
      <div className="card mb-5">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center">
            <Brain size={18} className="text-slate-400" />
          </div>
          <div>
            <p className="font-semibold text-slate-800">Assessment Saved</p>
            <p className="text-xs text-slate-500">Analysis is being prepared</p>
          </div>
        </div>
        <p className="text-sm text-slate-600 leading-relaxed bg-surface-50 rounded-xl p-4 border border-surface-200">
          Your pre-assessment has been saved successfully. We recommend booking an appointment
          with a guidance counselor who can review your responses and provide personalized support.
        </p>
      </div>
      <div className="p-4 bg-amber-50 border border-amber-200 rounded-xl mb-5">
        <p className="text-xs text-amber-700 leading-relaxed">{DISCLAIMER_STUDENT}</p>
      </div>
      <div className="space-y-2">
        <button onClick={handleBook} className="btn-primary w-full flex items-center justify-center gap-2">
          <CalendarDays size={16} /> Book an Appointment
        </button>
        <button onClick={() => navigate('/student/dashboard')}
          className="w-full text-center text-sm text-slate-400 hover:text-slate-600 py-2 transition-colors">
          Return to dashboard
        </button>
      </div>
    </div>
  )
}
