import { useEffect, useState } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import {
  ArrowLeft, ClipboardList, CalendarDays, BookOpen,
  AlertTriangle, CheckCircle2, Clock, ChevronRight,
  ExternalLink, Sparkles, Link2, BarChart3, Tag,
} from 'lucide-react'
import { preAssessmentAPI } from '@/api'
import { formatDate, formatTime, timeAgo, RISK_LEVEL_CONFIG, LIKERT_LABELS } from '@/lib/utils'
import StatusBadge from '@/components/ui/StatusBadge'
import ResourceTypeIcon from '@/components/ui/ResourceTypeIcon'

const DISCLAIMER_STUDENT = `The information generated by this pre-assessment is intended only to assist the Guidance Office in understanding your concerns and preparing for counseling sessions. The results are suggestive in nature and should be interpreted with discretion. They do not constitute professional counseling, diagnosis, treatment, or psychological evaluation. Only a qualified Guidance Counselor can properly assess your situation.`

export default function StudentPreAssessmentDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [assessment, setAssessment] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    preAssessmentAPI.getById(id)
      .then(({ data }) => setAssessment(data))
      .catch((err) => setError(err.response?.data?.message || 'Failed to load assessment'))
      .finally(() => setLoading(false))
  }, [id])

  if (loading) {
    return (
      <div className="animate-fade-in max-w-3xl mx-auto space-y-4">
        <div className="skeleton h-8 w-48 rounded-xl" />
        <div className="skeleton h-40 rounded-2xl" />
        <div className="skeleton h-32 rounded-2xl" />
        <div className="skeleton h-48 rounded-2xl" />
      </div>
    )
  }

  if (error) {
    return (
      <div className="animate-fade-in max-w-3xl mx-auto">
        <div className="card text-center py-12">
          <AlertTriangle size={40} className="text-red-400 mx-auto mb-3" />
          <p className="font-semibold text-slate-800 text-lg">Could not load assessment</p>
          <p className="text-slate-500 text-sm mt-1">{error}</p>
          <button onClick={() => navigate(-1)} className="btn-secondary mt-4">Go Back</button>
        </div>
      </div>
    )
  }

  const ar     = assessment?.assessmentResults
  const legacy = assessment?.aiRecommendations
  const riskCfg = ar?.riskLevel ? RISK_LEVEL_CONFIG[ar.riskLevel] : null
  const isUrgent =
    ar?.riskLevel === 'Critical' ||
    assessment?.urgencyLevel === 'Immediate' ||
    assessment?.urgencyLevel === 'Crisis' ||
    legacy?.urgencyFlag

  return (
    <div className="animate-fade-in max-w-5xl mx-auto">

      {/* Back + header */}
      <div className="mb-6">
        <button onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-sm text-slate-500 hover:text-slate-700 mb-4 transition-colors">
          <ArrowLeft size={16} /> Back
        </button>
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="page-title">Pre-Assessment Details</h1>
            <p className="text-slate-400 text-sm mt-0.5">{timeAgo(assessment?.createdAt)}</p>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            {riskCfg ? (
              <span className={`text-xs font-semibold px-3 py-1 rounded-full ${riskCfg.bg} ${riskCfg.color}`}>
                {riskCfg.label}
              </span>
            ) : (
              <span className="text-xs font-semibold px-3 py-1 rounded-full bg-slate-100 text-slate-600">
                {assessment?.urgencyLevel} Urgency
              </span>
            )}
            {isUrgent && (
              <span className="flex items-center gap-1 text-xs font-semibold px-3 py-1 rounded-full bg-red-100 text-red-700">
                <AlertTriangle size={12} /> Flagged
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Crisis banner */}
      {isUrgent && (
        <div className="mb-5 flex items-start gap-3 p-4 bg-red-50 border border-red-300 rounded-2xl">
          <AlertTriangle size={16} className="text-red-500 shrink-0 mt-0.5" />
          <p className="text-xs text-red-600 leading-relaxed">
            <strong>Immediate Support:</strong> If you feel unsafe, contact{' '}
            <strong>Hopeline PH: 02-8804-4673</strong> or visit the Guidance Office immediately.
          </p>
        </div>
      )}

      {/* Reference sections — two columns on desktop */}
      <div className="grid lg:grid-cols-2 gap-5 items-start mb-5 [&>.card]:mb-0">
      {/* Purpose of Visit */}
      {assessment?.purposeOfVisit?.length > 0 && (
        <div className="card border border-surface-200 mb-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-9 h-9 bg-primary-50 rounded-xl flex items-center justify-center shrink-0">
              <ClipboardList size={16} className="text-primary-600" />
            </div>
            <p className="font-semibold text-slate-800">Purpose of Visit</p>
          </div>
          <div className="flex flex-wrap gap-2">
            {assessment.purposeOfVisit.map((p) => (
              <span key={p} className="text-xs px-3 py-1.5 rounded-full bg-primary-100 text-primary-700 font-medium">{p}</span>
            ))}
            {assessment.purposeOfVisitOther && (
              <span className="text-xs px-3 py-1.5 rounded-full bg-primary-100 text-primary-700 font-medium">{assessment.purposeOfVisitOther}</span>
            )}
          </div>
        </div>
      )}

      {/* Likert Self-Assessment */}
      {assessment?.likertResponses?.length > 0 && (
        <div className="card border border-surface-200 mb-5">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-9 h-9 bg-amber-50 rounded-xl flex items-center justify-center shrink-0">
              <BarChart3 size={16} className="text-amber-600" />
            </div>
            <p className="font-semibold text-slate-800">Self-Assessment Responses</p>
          </div>
          <div className="space-y-2">
            {assessment.likertResponses.map((r, i) => (
              <div key={i} className="flex items-center justify-between gap-3 py-1.5 border-b border-slate-100 last:border-0">
                <p className="text-xs text-slate-600 flex-1">{i + 1}. {r.statement}</p>
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full shrink-0
                  ${r.score >= 4 ? 'bg-red-100 text-red-700' : r.score === 3 ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'}`}>
                  {r.score} – {LIKERT_LABELS[r.score]}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Concern Categories */}
      {assessment?.concernCategories?.length > 0 && (
        <div className="card border border-surface-200 mb-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-9 h-9 bg-slate-100 rounded-xl flex items-center justify-center shrink-0">
              <Tag size={16} className="text-slate-500" />
            </div>
            <p className="font-semibold text-slate-800">Selected Concern Categories</p>
          </div>
          <div className="flex flex-wrap gap-2">
            {assessment.concernCategories.map((c) => (
              <span key={c} className="text-xs px-2.5 py-1 rounded-full bg-slate-200 text-slate-700 font-medium">{c}</span>
            ))}
          </div>
        </div>
      )}

      {/* Concern Description */}
      <div className="card border border-surface-200 mb-5">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-9 h-9 bg-primary-50 rounded-xl flex items-center justify-center shrink-0">
            <ClipboardList size={16} className="text-primary-600" />
          </div>
          <p className="font-semibold text-slate-800">Your Description</p>
        </div>
        <div className="bg-surface-50 rounded-xl p-4 border border-surface-200">
          <p className="text-sm text-slate-700 leading-relaxed">{assessment?.concernDescription}</p>
        </div>
        {assessment?.concernDuration && (
          <p className="text-xs text-slate-500 mt-3">
            Duration experiencing this concern: <strong>{assessment.concernDuration}</strong>
          </p>
        )}
        {assessment?.expectedAssistance && (
          <div className="mt-3">
            <p className="text-xs font-semibold text-slate-500 mb-1">Expected assistance:</p>
            <p className="text-sm text-slate-600 bg-surface-50 rounded-xl p-3 border border-surface-200">{assessment.expectedAssistance}</p>
          </div>
        )}
        {assessment?.urgencyLevel && (
          <p className="text-xs text-slate-500 mt-3">
            Self-reported urgency: <strong>{assessment.urgencyLevel}</strong>
          </p>
        )}
      </div>
      </div>{/* end reference sections grid */}

      {/* Assessment Results — new engine output */}
      {ar && (
        <div className="card border border-primary-200 bg-primary-50/10 mb-5">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400 bg-slate-100 px-2 py-0.5 rounded-full">
              Preliminary Guidance Support Information
            </span>
          </div>

          <div className="grid grid-cols-2 gap-3 mt-4 mb-4">
            <div className="bg-white rounded-xl border border-slate-200 p-3">
              <p className="text-xs text-slate-400 mb-1">Concern Area</p>
              <p className="text-sm font-semibold text-slate-800">{ar.detectedCategory}</p>
              <p className="text-[10px] text-slate-400 mt-1 italic">The responses may indicate this area.</p>
            </div>
            {riskCfg && (
              <div className={`rounded-xl border ${riskCfg.border} ${riskCfg.bg} p-3`}>
                <p className="text-xs text-slate-400 mb-1">Risk Level</p>
                <p className={`text-sm font-semibold ${riskCfg.color}`}>{riskCfg.label}</p>
              </div>
            )}
          </div>

          {ar.riskFactors?.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-slate-500 mb-2">Areas that may warrant further exploration:</p>
              <ul className="space-y-1.5">
                {ar.riskFactors.map((f, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-slate-600">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary-400 mt-1 shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {ar.studentSummary && (
            <div className="mb-4 p-4 bg-white rounded-xl border border-primary-100">
              <div className="flex items-center gap-1.5 mb-1.5">
                <Sparkles size={12} className="text-primary-400" />
                <p className="text-xs font-semibold text-primary-600">A Note for You</p>
              </div>
              <p className="text-sm text-slate-600 italic leading-relaxed">{ar.studentSummary}</p>
            </div>
          )}

          {ar.suggestedResources?.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-slate-500 mb-2">Suggested resources for consideration:</p>
              <div className="space-y-2">
                {ar.suggestedResources.map((r, i) => (
                  <div key={i} className="flex items-start gap-3 p-3 bg-white rounded-xl border border-slate-200">
                    <span className="w-8 h-8 rounded-lg bg-primary-50 flex items-center justify-center shrink-0">
                      <ResourceTypeIcon type={r.type} size={16} className="text-primary-500" />
                    </span>
                    <div>
                      <p className="text-sm font-semibold text-slate-800">{r.title}</p>
                      {r.description && <p className="text-xs text-slate-500 mt-0.5">{r.description}</p>}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {ar.suggestedNextAction && (
            <div className="p-3 bg-white rounded-xl border border-slate-200">
              <p className="text-xs font-semibold text-slate-400 mb-1">Suggested next action:</p>
              <p className="text-sm text-slate-700">{ar.suggestedNextAction}</p>
            </div>
          )}
        </div>
      )}

      {/* Legacy AI fallback (old submissions) */}
      {!ar && legacy && (
        <div className="card border border-primary-200 mb-5">
          <div className="flex items-center gap-2 mb-3">
            <Sparkles size={15} className="text-primary-400" />
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">AI Recommendation</p>
          </div>
          {legacy.studentFacingMessage && (
            <p className="text-sm text-slate-600 mb-3 leading-relaxed bg-surface-50 rounded-xl p-3 border border-surface-200">
              {legacy.studentFacingMessage}
            </p>
          )}
          {legacy.studentResources?.length > 0 && (
            <div className="space-y-2">
              {legacy.studentResources.map((res, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-surface-50 rounded-xl border border-surface-200">
                  <BookOpen size={14} className="text-slate-400 mt-0.5 shrink-0" />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-slate-800">{res.title}</p>
                    {res.description && <p className="text-xs text-slate-500 mt-0.5">{res.description}</p>}
                  </div>
                  {res.link && (
                    <a href={res.link} target="_blank" rel="noopener noreferrer" className="shrink-0 text-primary-500">
                      <ExternalLink size={14} />
                    </a>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Disclaimer */}
      <div className="card border border-amber-200 bg-amber-50/30 mb-5">
        <p className="text-xs font-semibold text-amber-800 mb-1.5">Important Notice</p>
        <p className="text-xs text-amber-700 leading-relaxed">{DISCLAIMER_STUDENT}</p>
      </div>

      {/* Linked appointment */}
      {assessment?.appointmentId ? (
        <div className="card border border-emerald-200 bg-emerald-50/40 mb-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-9 h-9 bg-emerald-100 rounded-xl flex items-center justify-center">
              <Link2 size={16} className="text-emerald-600" />
            </div>
            <div>
              <p className="font-semibold text-slate-800 text-sm">Linked to an Appointment</p>
              <p className="text-xs text-slate-500">Your counselor has access to this assessment</p>
            </div>
            <span className="badge-pill ml-auto bg-emerald-100 text-emerald-700 normal-case">
              <CheckCircle2 size={13} /> Linked
            </span>
          </div>
          {assessment.appointmentId?.type && (
            <div className="flex items-center justify-between p-3 bg-white rounded-xl border border-emerald-200">
              <div className="flex items-center gap-3">
                <CalendarDays size={15} className="text-primary-500" />
                <div>
                  <p className="text-sm font-semibold text-slate-800">{assessment.appointmentId.type}</p>
                  <p className="text-xs text-slate-500">
                    {formatDate(assessment.appointmentId.date)} · {formatTime(assessment.appointmentId.startTime)}
                  </p>
                </div>
              </div>
              <StatusBadge status={assessment.appointmentId.status} />
            </div>
          )}
        </div>
      ) : (
        <div className="card border border-surface-200 mb-5">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-slate-100 rounded-xl flex items-center justify-center shrink-0">
              <Link2 size={16} className="text-slate-400" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-semibold text-slate-700">Not linked to an appointment</p>
              <p className="text-xs text-slate-400 mt-0.5">
                Book an appointment and link this assessment so your counselor can prepare.
              </p>
            </div>
            <Link to={`/student/book?preAssessmentId=${id}`} className="btn-secondary text-sm shrink-0 flex items-center gap-1 border border-surface-300">
              Book <ChevronRight size={13} />
            </Link>
          </div>
        </div>
      )}

      {/* Legacy questionnaire responses (old format) */}
      {!assessment?.likertResponses?.length && assessment?.responses?.length > 0 && (
        <div className="card border border-surface-200 mb-5">
          <h2 className="font-display font-semibold text-slate-900 mb-4">Your Responses</h2>
          <div className="space-y-4">
            {assessment.responses.map((r, i) => (
              <div key={i} className="pb-4 border-b border-surface-100 last:border-0 last:pb-0">
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-1.5">Q{i + 1}</p>
                <p className="text-sm font-medium text-slate-700 mb-2">{r.question}</p>
                <p className="text-sm text-slate-600 bg-surface-50 rounded-xl p-3 border border-surface-200">{r.answer}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="flex items-center gap-2 text-xs text-slate-400 pb-8">
        <Clock size={12} />
        <span>Submitted {timeAgo(assessment?.createdAt)}</span>
        {assessment?.status === 'reviewed' && (
          <>
            <span>·</span>
            <CheckCircle2 size={12} className="text-emerald-400" />
            <span className="text-emerald-500">Reviewed by counselor</span>
          </>
        )}
      </div>
    </div>
  )
}
